/*
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalWorkflow.parser.antlr;

import com.google.inject.Inject;
import de.nak.xtext.hausarbeit.rentalWorkflow.parser.antlr.internal.InternalRentalWorkflowParser;
import de.nak.xtext.hausarbeit.rentalWorkflow.services.RentalWorkflowGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RentalWorkflowParser extends AbstractAntlrParser {

	@Inject
	private RentalWorkflowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRentalWorkflowParser createParser(XtextTokenStream stream) {
		return new InternalRentalWorkflowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RentalWorkflow";
	}

	public RentalWorkflowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RentalWorkflowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
