/**
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalSystem.scoping;

import de.nak.xtext.hausarbeit.rentalSystem.scoping.AbstractRentalSystemScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RentalSystemScopeProvider extends AbstractRentalSystemScopeProvider {
}
