/*
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalWorkflow


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RentalWorkflowStandaloneSetup extends RentalWorkflowStandaloneSetupGenerated {

	def static void doSetup() {
		new RentalWorkflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
