/*
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalWorkflow.tests

import com.google.inject.Inject
import de.nak.xtext.hausarbeit.rentalWorkflow.rentalWorkflow.RentalWorkflow
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(RentalWorkflowInjectorProvider)
class RentalWorkflowParsingTest{

	@Inject
	ParseHelper<RentalWorkflow> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
