/**
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalWorkflow;

import de.nak.xtext.hausarbeit.rentalWorkflow.RentalWorkflowStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RentalWorkflowStandaloneSetup extends RentalWorkflowStandaloneSetupGenerated {
  public static void doSetup() {
    RentalWorkflowStandaloneSetup _rentalWorkflowStandaloneSetup = new RentalWorkflowStandaloneSetup();
    _rentalWorkflowStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
