/*
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalSystem.validation

import de.nak.xtext.hausarbeit.rentalSystem.rentalSystem.Deal
import de.nak.xtext.hausarbeit.rentalSystem.rentalSystem.RentalSystemPackage
import org.eclipse.xtext.validation.Check


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DealValidator extends AbstractRentalSystemValidator {
	
	public static final String DEAL__UPPER_CASE_NAME = "de.nak.xtext.hausarbeit.rentalSystem.validation.dealUpperCaseName";
	
	@Check
	def dealShallStartWithLowerCase(Deal deal) {
		if(Character.isUpperCase(deal.name.charAt(0))) {
		    	warning(
		    		"The attribute should start with a lower case.", 
		    		RentalSystemPackage.Literals.DEAL__NAME, 
		    		DEAL__UPPER_CASE_NAME, 
		    		deal.name
		    	) 
		  }
	}

}