/*
 * generated by Xtext 2.9.2
 */
package de.nak.xtext.hausarbeit.rentalSystem.validation

import de.nak.xtext.hausarbeit.rentalSystem.rentalSystem.RentalSystemPackage
import de.nak.xtext.hausarbeit.rentalSystem.rentalSystem.RentalType
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RentalTypeValidator extends AbstractRentalSystemValidator {
	
	public static final String RENTAL_TYPE__UPPER_CASE_NAME = "de.nak.xtext.hausarbeit.rentalSystem.validation.rentalTypeUpperCaseName";
	
	@Check
	def rentalTypeShallStartWithLowerCase(RentalType rentalType) {
		if(Character.isUpperCase(rentalType.name.charAt(0))) {
		    	warning(
		    		"The attribute should start with a lower case.", 
		    		RentalSystemPackage.Literals.ATTRIBUTE__NAME, 
		    		RENTAL_TYPE__UPPER_CASE_NAME, 
		    		rentalType.name
		    	) 
		  }
	}
	
}